#!/bin/sh
echo "vm" > /etc/hostname
echo "127.0.0.1    localhost vm" > /etc/hosts

echo "root:password" | chpasswd
echo "user:password" | chpasswd

echo nameserver 8.8.8.8 > /etc/resolv.conf

exec /sbin/init
